declare @old varchar(100)
set @old = 'https://mosaic.haworth.com/'
declare @new varchar(100)
set @new = 'http://vmspw6:7777/'
declare @mosaic varchar(100)
set @mosaic = @old + '%'

update AllUserData set nvarchar1 = replace(nvarchar1,@old,@new) from AllUserData where nvarchar1 like @mosaic
update AllUserData set nvarchar2 = replace(nvarchar2,@old,@new) from AllUserData where nvarchar2 like @mosaic
update AllUserData set nvarchar3 = replace(nvarchar3,@old,@new) from AllUserData where nvarchar3 like @mosaic
update AllUserData set nvarchar4 = replace(nvarchar4,@old,@new) from AllUserData where nvarchar4 like @mosaic
update AllUserData set nvarchar5 = replace(nvarchar5,@old,@new) from AllUserData where nvarchar5 like @mosaic
update AllUserData set nvarchar6 = replace(nvarchar6,@old,@new) from AllUserData where nvarchar6 like @mosaic
update AllUserData set nvarchar7 = replace(nvarchar7,@old,@new) from AllUserData where nvarchar7 like @mosaic
update AllUserData set nvarchar8 = replace(nvarchar8,@old,@new) from AllUserData where nvarchar8 like @mosaic
update AllUserData set nvarchar9 = replace(nvarchar9,@old,@new) from AllUserData where nvarchar9 like @mosaic
update AllUserData set nvarchar10 = replace(nvarchar10,@old,@new) from AllUserData where nvarchar10 like @mosaic
update AllUserData set nvarchar11 = replace(nvarchar11,@old,@new) from AllUserData where nvarchar11 like @mosaic
update AllUserData set nvarchar12 = replace(nvarchar12,@old,@new) from AllUserData where nvarchar12 like @mosaic
update AllUserData set nvarchar13 = replace(nvarchar13,@old,@new) from AllUserData where nvarchar13 like @mosaic
update AllUserData set nvarchar14 = replace(nvarchar14,@old,@new) from AllUserData where nvarchar14 like @mosaic
update AllUserData set nvarchar15 = replace(nvarchar15,@old,@new) from AllUserData where nvarchar15 like @mosaic
update AllUserData set nvarchar16 = replace(nvarchar16,@old,@new) from AllUserData where nvarchar16 like @mosaic
update AllUserData set nvarchar17 = replace(nvarchar17,@old,@new) from AllUserData where nvarchar17 like @mosaic
update AllUserData set nvarchar18 = replace(nvarchar18,@old,@new) from AllUserData where nvarchar18 like @mosaic
update AllUserData set nvarchar19 = replace(nvarchar19,@old,@new) from AllUserData where nvarchar19 like @mosaic
update AllUserData set nvarchar20 = replace(nvarchar20,@old,@new) from AllUserData where nvarchar20 like @mosaic
update AllUserData set nvarchar21 = replace(nvarchar21,@old,@new) from AllUserData where nvarchar21 like @mosaic
update AllUserData set nvarchar22 = replace(nvarchar22,@old,@new) from AllUserData where nvarchar22 like @mosaic
update AllUserData set nvarchar23 = replace(nvarchar23,@old,@new) from AllUserData where nvarchar23 like @mosaic
update AllUserData set nvarchar24 = replace(nvarchar24,@old,@new) from AllUserData where nvarchar24 like @mosaic
update AllUserData set nvarchar25 = replace(nvarchar25,@old,@new) from AllUserData where nvarchar25 like @mosaic
update AllUserData set nvarchar26 = replace(nvarchar26,@old,@new) from AllUserData where nvarchar26 like @mosaic
update AllUserData set nvarchar27 = replace(nvarchar27,@old,@new) from AllUserData where nvarchar27 like @mosaic
update AllUserData set nvarchar28 = replace(nvarchar28,@old,@new) from AllUserData where nvarchar28 like @mosaic
update AllUserData set nvarchar29 = replace(nvarchar29,@old,@new) from AllUserData where nvarchar29 like @mosaic
update AllUserData set nvarchar30 = replace(nvarchar30,@old,@new) from AllUserData where nvarchar30 like @mosaic
update AllUserData set nvarchar31 = replace(nvarchar31,@old,@new) from AllUserData where nvarchar31 like @mosaic
update AllUserData set nvarchar32 = replace(nvarchar32,@old,@new) from AllUserData where nvarchar32 like @mosaic
update AllUserData set nvarchar33 = replace(nvarchar33,@old,@new) from AllUserData where nvarchar33 like @mosaic
update AllUserData set nvarchar34 = replace(nvarchar34,@old,@new) from AllUserData where nvarchar34 like @mosaic
update AllUserData set nvarchar35 = replace(nvarchar35,@old,@new) from AllUserData where nvarchar35 like @mosaic
update AllUserData set nvarchar36 = replace(nvarchar36,@old,@new) from AllUserData where nvarchar36 like @mosaic
update AllUserData set nvarchar37 = replace(nvarchar37,@old,@new) from AllUserData where nvarchar37 like @mosaic
update AllUserData set nvarchar38 = replace(nvarchar38,@old,@new) from AllUserData where nvarchar38 like @mosaic
update AllUserData set nvarchar39 = replace(nvarchar39,@old,@new) from AllUserData where nvarchar39 like @mosaic
update AllUserData set nvarchar40 = replace(nvarchar40,@old,@new) from AllUserData where nvarchar40 like @mosaic
update AllUserData set nvarchar41 = replace(nvarchar41,@old,@new) from AllUserData where nvarchar41 like @mosaic
update AllUserData set nvarchar42 = replace(nvarchar42,@old,@new) from AllUserData where nvarchar42 like @mosaic
update AllUserData set nvarchar43 = replace(nvarchar43,@old,@new) from AllUserData where nvarchar43 like @mosaic
update AllUserData set nvarchar44 = replace(nvarchar44,@old,@new) from AllUserData where nvarchar44 like @mosaic
update AllUserData set nvarchar45 = replace(nvarchar45,@old,@new) from AllUserData where nvarchar45 like @mosaic
update AllUserData set nvarchar46 = replace(nvarchar46,@old,@new) from AllUserData where nvarchar46 like @mosaic
update AllUserData set nvarchar47 = replace(nvarchar47,@old,@new) from AllUserData where nvarchar47 like @mosaic
update AllUserData set nvarchar48 = replace(nvarchar48,@old,@new) from AllUserData where nvarchar48 like @mosaic
update AllUserData set nvarchar49 = replace(nvarchar49,@old,@new) from AllUserData where nvarchar49 like @mosaic
update AllUserData set nvarchar50 = replace(nvarchar50,@old,@new) from AllUserData where nvarchar50 like @mosaic
update AllUserData set nvarchar51 = replace(nvarchar51,@old,@new) from AllUserData where nvarchar51 like @mosaic
update AllUserData set nvarchar52 = replace(nvarchar52,@old,@new) from AllUserData where nvarchar52 like @mosaic
update AllUserData set nvarchar53 = replace(nvarchar53,@old,@new) from AllUserData where nvarchar53 like @mosaic
update AllUserData set nvarchar54 = replace(nvarchar54,@old,@new) from AllUserData where nvarchar54 like @mosaic
update AllUserData set nvarchar55 = replace(nvarchar55,@old,@new) from AllUserData where nvarchar55 like @mosaic
update AllUserData set nvarchar56 = replace(nvarchar56,@old,@new) from AllUserData where nvarchar56 like @mosaic
update AllUserData set nvarchar57 = replace(nvarchar57,@old,@new) from AllUserData where nvarchar57 like @mosaic
update AllUserData set nvarchar58 = replace(nvarchar58,@old,@new) from AllUserData where nvarchar58 like @mosaic
update AllUserData set nvarchar59 = replace(nvarchar59,@old,@new) from AllUserData where nvarchar59 like @mosaic
update AllUserData set nvarchar60 = replace(nvarchar60,@old,@new) from AllUserData where nvarchar60 like @mosaic
update AllUserData set nvarchar61 = replace(nvarchar61,@old,@new) from AllUserData where nvarchar61 like @mosaic
